### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by lchski** [YOWCT/Civic-Tech-Course#1]
Hia! I’m supposed to be studying for something right now, but this course seemed much more interesting 😉 

The links in the main README, “[browse these pages](https://yowct.github.io/Civic-Tech-Course/)” and “[slides](https://yowct.github.io/Civic-Tech-Course/Curiosity/slides-remark/)” are broken. I think it might have to do with the DNS changes that went on to get the new site up... I’m not sure what @xander-miller had to do to make it work, but he might be able to chime in and suggest a solution.

**Comment by xander-miller** [comment]
Yes, it does have to do with the domain name change. The url to view this repository through github pages is now. http://ottawacivictech.ca/Digital-Government-Civic-Tech-Open-Curriculum/

As a first step the absolute referenced links have to be updated to the new url. There might be something else going on with the slides though. Once the links have been updated I will have to take a look.

**Comment by xander-miller** [comment]
@mgifford I found the slides are on github pages here

http://ottawacivictech.ca/Digital-Government-Civic-Tech-Open-Curriculum/Curiosity/slides.html#1

I've noticed two changes. The domain name has changed but it also seems the the repository name has changed at some point two which also changed from Civic-Tech-Course to Digital-Government-Civic-Tech-Open-Curriculum which also effects the absolute links

**Comment by xander-miller** [comment]
This issue should be resolved by pull request #3

**Comment by mgifford** [comment]
In that case.. I'll just fix the link on the page! Thanks. this is great.
